version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    review-labels:
      - "dependencies"
      - "ReactWeb"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    review-labels:
      - "github_actions"
      - "ReactWeb"
    commit-message:
      prefix: "deps"
      include: "scope"
