server {
    listen 80;
    server_name localhost;

    # Sirve los archivos estáticos de React
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;  # Reescribe rutas para SPA
    }

    # Proxy para las peticiones a la API
    location /api/ {
        proxy_pass http://new-api-svc:80;  # Redirige al servicio interno de Kubernetes
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Opcional: Manejo de errores
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}