apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-web
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-web
  template:
    metadata:
      labels:
        app: react-web
    spec:
      containers:
      - name: react-web
        image: erizo9/reactweb:834ed26e6ca8c7c069b305e3c0071ecf81ccf212
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
        - name: NODE_ENV
          value: "production"
        volumeMounts:
        - name: ssl-certs
          mountPath: "/etc/nginx/certs"
          readOnly: true
      volumes:
      - name: ssl-certs
        secret:
          secretName: react-web-ssl
          items:
          - key: tls.crt
            path: origin-cert.pem
          - key: tls.key
            path: origin-key.key
---
apiVersion: v1
kind: Service
metadata:
  name: react-web-svc
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31876
    name: http
  - port: 443
    targetPort: 443
    nodePort: 30443  # Asegúrate de que este puerto esté libre
    name: https
  selector:
    app: react-web
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: react-web-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: react-web
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
