apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-web-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: atrapo.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: react-web-svc
            port:
              number: 443  # Cambia de 80 a 443
  - host: www.atrapo.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: react-web-svc
            port:
              number: 443  # Cambia de 80 a 443
  tls:
  - hosts:
    - atrapo.io
    - www.atrapo.io
    secretName: react-web-ssl
