apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: react-web-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: react-web
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
  egress:
  - ports:
    - port: 80
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app: new-api
  - ports:
    - port: 53
      protocol: UDP
    to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
  - ports:
    - port: 443
      protocol: TCP
    - port: 80
      protocol: TCP
